Added mount/unmount commands
Instructions:

sudo insmod myfs.ko
sudo mount -t myfs myfile mnt -o loop
sudo umount mnt
sudo rmmod myfs.ko

Error: mounting myfs. Need to correct this.

[  150.316309] myfs: module license 'CC0' taints kernel.
[  150.316313] Disabling lock debugging due to kernel taint
[  150.316336] myfs: module verification failed: signature and/or  required key missing - tainting kernel
[  150.316756] myfs_init()
[  150.316762] myfs_init() MYFS Registered
[  184.385228] myfs_mount()
[  184.385233] Error mounting MyFS
[  192.362604] myfs_mount()
[  192.362618] myfs_fill_super()
[  192.362620] myfs_get_inode()
[  192.362621] Incrementing the inode dir link count
[  192.362624] myfs_mount() MyFS successfully mounted on [/dev/loop0]
[  216.456092] myfs_kill_superblock()
[  216.456097] MyFS Super Block Destroyed, Unmount Successful